### ISSUE TITLE
Vulkan and LibEGL issue ?

### ISSUE THREAD

**Issue by kiberonlabsdev** [dgtlmoon/sockpuppetbrowser#31]
I seem to be having an issue running this in kubernetes. Weirdly when I use it to show browser steps and set the Visual Filter Selection in my change-detection instance it works fine, however when it triggers the check on the timer I get a 999 response reported and it seems to break 

Image: 
docker.io/dgtlmoon/sockpuppetbrowser@sha256:df8d9d02e1efa93d7824e81222ee638e7d0dbb0ef132bc277dc01c969e82d57e

Env vars

MAX_CONCURRENT_CHROME_PROCESSES : 10
SCREEN_DEPTH : 16
SCREEN_HEIGHT : 1024
SCREEN_WIDTH : 1920

```
25-06-26 20:30:40.823 | DEBUG    | __main__:launchPuppeteerChromeProxy:490 - WebSocket ID: 6d5194c5-7f97-428e-9bd2-9715bf3ed2c3 Got new incoming connection ID from 10.42.3.114:37324 (/?headful=true)
2025-06-26 20:30:40.823 | DEBUG    | __main__:launch_chrome:148 - No --window-size in start query, falling back to env var --window-size=1920,1024
2025-06-26 20:30:40.823 | DEBUG    | __main__:launch_chrome:162 - No user-data-dir in query, using /tmp/chrome-puppeteer-proxyo7h1wfoh
2025-06-26 20:30:40.823 | DEBUG    | __main__:launch_chrome:171 - Using headful mode with xvfb-run (auto display allocation)
2025-06-26 20:30:40.954 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 6d5194c5-7f97-428e-9bd2-9715bf3ed2c3 Chrome stderr PID 896: [908:925:0626/203040.954192:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2025-06-26 20:30:41.029 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 6d5194c5-7f97-428e-9bd2-9715bf3ed2c3 Chrome stderr PID 896: [908:929:0626/203041.029669:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2025-06-26 20:30:41.030 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 6d5194c5-7f97-428e-9bd2-9715bf3ed2c3 Chrome stderr PID 896: [908:929:0626/203041.029724:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2025-06-26 20:30:41.031 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 6d5194c5-7f97-428e-9bd2-9715bf3ed2c3 Chrome stderr PID 896: [908:925:0626/203041.031396:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
2025-06-26 20:30:41.031 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 6d5194c5-7f97-428e-9bd2-9715bf3ed2c3 Chrome stderr PID 896: [908:925:0626/203041.031419:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
2025-06-26 20:30:41.031 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 6d5194c5-7f97-428e-9bd2-9715bf3ed2c3 Chrome stderr PID 896: [908:925:0626/203041.031430:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
2025-06-26 20:30:41.031 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 6d5194c5-7f97-428e-9bd2-9715bf3ed2c3 Chrome stderr PID 896: [908:925:0626/203041.031459:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
2025-06-26 20:30:41.033 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 6d5194c5-7f97-428e-9bd2-9715bf3ed2c3 Chrome stderr PID 896: [908:935:0626/203041.033494:ERROR:zygote_host_impl_linux.cc(273)] Failed to adjust OOM score of renderer with pid 937: Permission denied (13)
2025-06-26 20:30:41.038 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 6d5194c5-7f97-428e-9bd2-9715bf3ed2c3 Chrome stderr PID 896: [908:908:0626/203041.033708:ERROR:policy_logger.cc(157)] :components/enterprise/browser/controller/chrome_browser_cloud_management_controller.cc(163) Cloud management controller initialization aborted as CBCM is not enabled.
2025-06-26 20:30:41.039 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 6d5194c5-7f97-428e-9bd2-9715bf3ed2c3 Chrome stderr PID 896: [908:925:0626/203041.039298:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
2025-06-26 20:30:41.039 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 6d5194c5-7f97-428e-9bd2-9715bf3ed2c3 Chrome stderr PID 896: [908:925:0626/203041.039315:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
2025-06-26 20:30:41.050 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 6d5194c5-7f97-428e-9bd2-9715bf3ed2c3 Chrome stderr PID 896: [908:935:0626/203041.050266:ERROR:zygote_host_impl_linux.cc(273)] Failed to adjust OOM score of renderer with pid 940: Permission denied (13)
2025-06-26 20:30:41.058 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 6d5194c5-7f97-428e-9bd2-9715bf3ed2c3 Chrome stderr PID 896: 
2025-06-26 20:30:41.059 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 6d5194c5-7f97-428e-9bd2-9715bf3ed2c3 Chrome stderr PID 896: DevTools listening on ws://127.0.0.1:10002/devtools/browser/eadac82e-0df9-44c9-9186-4fd422d46358
2025-06-26 20:30:41.064 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 6d5194c5-7f97-428e-9bd2-9715bf3ed2c3 Chrome stderr PID 896: [908:925:0626/203041.064153:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
2025-06-26 20:30:41.064 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 6d5194c5-7f97-428e-9bd2-9715bf3ed2c3 Chrome stderr PID 896: [908:925:0626/203041.064167:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
2025-06-26 20:30:41.077 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 6d5194c5-7f97-428e-9bd2-9715bf3ed2c3 Chrome stderr PID 896: [908:935:0626/203041.076966:ERROR:zygote_host_impl_linux.cc(273)] Failed to adjust OOM score of renderer with pid 975: Permission denied (13)
2025-06-26 20:30:41.079 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 6d5194c5-7f97-428e-9bd2-9715bf3ed2c3 Chrome stderr PID 896: [908:935:0626/203041.079243:ERROR:zygote_host_impl_linux.cc(273)] Failed to adjust OOM score of renderer with pid 981: Permission denied (13)

2025-06-26 20:30:41.867 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 6d5194c5-7f97-428e-9bd2-9715bf3ed2c3 Chrome stderr PID 896: [908:935:0626/203041.867187:ERROR:zygote_host_impl_linux.cc(273)] Failed to adjust OOM score of renderer with pid 1193: Permission denied (13)
2025-06-26 20:30:41.868 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 6d5194c5-7f97-428e-9bd2-9715bf3ed2c3 Chrome stderr PID 896: [908:935:0626/203041.868039:ERROR:zygote_host_impl_linux.cc(273)] Failed to adjust OOM score of renderer with pid 1195: Permission denied (13)
25-06-26 20:30:48.629 | DEBUG    | __main__:cleanup_chrome_by_pid:297 - WebSocket ID: 6d5194c5-7f97-428e-9bd2-9715bf3ed2c3 Cleaning up Chrome subprocess PID 896
2025-06-26 20:30:48.630 | DEBUG    | __main__:cleanup_chrome_by_pid:318 - WebSocket ID: 6d5194c5-7f97-428e-9bd2-9715bf3ed2c3 - Killing 15 Chrome child processes
2025-06-26 20:30:48.631 | ERROR    | __main__:cleanup_chrome_by_pid:377 - WebSocket ID: 6d5194c5-7f97-428e-9bd2-9715bf3ed2c3 - Error in Chrome cleanup: Passing coroutines is forbidden, use tasks explicitly.
2025-06-26 20:30:48.631 | DEBUG    | __main__:close_socket:268 - WebSocket: 6d5194c5-7f97-428e-9bd2-9715bf3ed2c3 Closing websocket to puppeteer
/usr/lib/python3.11/asyncio/events.py:84: RuntimeWarning: coroutine 'wait_for' was never awaited
  self._context.run(self._callback, *self._args)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2025-06-26 20:30:54.169 | CRITICAL | __main__:log_stream:220 - WebSocket ID: c31f3def-fcd3-4745-8b71-57adeebe3609 Chrome stderr PID 407: Warning: vkCreateInstance: Found no drivers!
2025-06-26 20:30:54.170 | CRITICAL | __main__:log_stream:220 - WebSocket ID: c31f3def-fcd3-4745-8b71-57adeebe3609 Chrome stderr PID 407: Warning: vkCreateInstance failed with VK_ERROR_INCOMPATIBLE_DRIVER
2025-06-26 20:30:54.170 | CRITICAL | __main__:log_stream:220 - WebSocket ID: c31f3def-fcd3-4745-8b71-57adeebe3609 Chrome stderr PID 407: at CheckVkSuccessImpl (../../third_party/dawn/src/dawn/native/vulkan/VulkanError.cpp:88)
2025-06-26 20:30:54.170 | CRITICAL | __main__:log_stream:220 - WebSocket ID: c31f3def-fcd3-4745-8b71-57adeebe3609 Chrome stderr PID 407: at CreateVkInstance (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:458)
2025-06-26 20:30:54.170 | CRITICAL | __main__:log_stream:220 - WebSocket ID: c31f3def-fcd3-4745-8b71-57adeebe3609 Chrome stderr PID 407: at Initialize (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:344)
2025-06-26 20:30:54.170 | CRITICAL | __main__:log_stream:220 - WebSocket ID: c31f3def-fcd3-4745-8b71-57adeebe3609 Chrome stderr PID 407: at Create (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:266)
2025-06-26 20:30:54.171 | CRITICAL | __main__:log_stream:220 - WebSocket ID: c31f3def-fcd3-4745-8b71-57adeebe3609 Chrome stderr PID 407: at operator() (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:521)
2025-06-26 20:30:54.171 | CRITICAL | __main__:log_stream:220 - WebSocket ID: c31f3def-fcd3-4745-8b71-57adeebe3609 Chrome stderr PID 407: 
2025-06-26 20:30:54.171 | CRITICAL | __main__:log_stream:220 - WebSocket ID: c31f3def-fcd3-4745-8b71-57adeebe3609 Chrome stderr PID 407: Warning: Failed to load libEGL.so
2025-06-26 20:30:54.171 | CRITICAL | __main__:log_stream:220 - WebSocket ID: c31f3def-fcd3-4745-8b71-57adeebe3609 Chrome stderr PID 407: at DiscoverPhysicalDevices (../../third_party/dawn/src/dawn/native/opengl/BackendGL.cpp:61)
2025-06-26 20:30:54.171 | CRITICAL | __main__:log_stream:220 - WebSocket ID: c31f3def-fcd3-4745-8b71-57adeebe3609 Chrome stderr PID 407: 
```

**Comment by gilbrotheraway** [comment]
getting this same line here on docker/linux

`2025-08-22 00:40:06.278 | CRITICAL | __main__:log_stream:220 - WebSocket ID: a6c075be-f8a6-4089-b9ff-79c61e131922 Chrome stderr PID 62: [0822/004006.278332:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory`

**Comment by gilbrotheraway** [comment]
here's an LLM suggestion to fix it:

2. Install D-Bus in Your Docker Container
To fix the D-Bus connection error, you should install the dbus package in your Docker container. Open your Dockerfile and add the following to your apk add or apt-get install command:

Dockerfile

RUN apk add --no-cache dbus
Then, you'll need to start the D-Bus daemon in your entrypoint.sh script before you start your Python server. Add these lines to the top of the script:

Bash

mkdir -p /var/run/dbus
dbus-daemon --config-file=/usr/share/dbus-1/system.conf --print-address

**Comment by amigthea** [comment]
I'm getting similar errors each time changedetection execute a check

```
2025-11-15 15:05:57.004 | DEBUG    | __main__:launchPuppeteerChromeProxy:490 - WebSocket ID: 611eff89-fc06-44a9-a2bd-9dee72f18870 Got new incoming connection ID from 127.0.0.1:54938 (/?stealth=1&--disable-web-security=true)
2025-11-15 15:05:57.004 | DEBUG    | __main__:launch_chrome:148 - No --window-size in start query, falling back to env var --window-size=1920,1024
2025-11-15 15:05:57.004 | DEBUG    | __main__:launch_chrome:162 - No user-data-dir in query, using /tmp/chrome-puppeteer-proxyzcwlpe8y
2025-11-15 15:05:57.115 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 611eff89-fc06-44a9-a2bd-9dee72f18870 Chrome stderr PID 7557: [1115/150557.115349:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2025-11-15 15:05:57.121 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 611eff89-fc06-44a9-a2bd-9dee72f18870 Chrome stderr PID 7557: [1115/150557.120784:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2025-11-15 15:05:57.121 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 611eff89-fc06-44a9-a2bd-9dee72f18870 Chrome stderr PID 7557: [1115/150557.120940:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2025-11-15 15:05:57.126 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 611eff89-fc06-44a9-a2bd-9dee72f18870 Chrome stderr PID 7557:
2025-11-15 15:05:57.128 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 611eff89-fc06-44a9-a2bd-9dee72f18870 Chrome stderr PID 7557: DevTools listening on ws://127.0.0.1:10131/devtools/browser/bca95321-2277-4e52-be88-c6fb9a48e627
2025-11-15 15:05:58.007 | DEBUG    | __main__:_request_retry:422 - WebSocket ID: 611eff89-fc06-44a9-a2bd-9dee72f18870 - _request_retry attempt 1/20 for http://localhost:10131/json/version (timeout=5.0s)
2025-11-15 15:05:58.009 | DEBUG    | __main__:_request_retry:434 - WebSocket ID: 611eff89-fc06-44a9-a2bd-9dee72f18870 - _request_retry succeeded after 1 attempts in 1.00s
2025-11-15 15:05:58.009 | DEBUG    | __main__:launchPuppeteerChromeProxy:581 - WebSocket ID: 611eff89-fc06-44a9-a2bd-9dee72f18870 proxying to local Chrome instance via CDP ws://localhost:10131/devtools/browser/bca95321-2277-4e52-be88-c6fb9a48e627
2025-11-15 15:05:58.051 | DEBUG    | __main__:puppeteerToHere:685 - 611eff89-fc06-44a9-a2bd-9dee72f18870 Page.navigate request called to 'https://archlinux.org/packages/extra/x86_64/mesa/'
2025-11-15 15:05:59.257 | INFO     | __main__:stats_thread_func:704 - Connections: Active count 1 of max 10, Total processed: 132.
2025-11-15 15:05:59.259 | INFO     | __main__:stats_thread_func:727 - Process info: 1 child processes
2025-11-15 15:06:02.261 | INFO     | __main__:stats_thread_func:704 - Connections: Active count 1 of max 10, Total processed: 132.
2025-11-15 15:06:02.262 | INFO     | __main__:stats_thread_func:727 - Process info: 1 child processes
2025-11-15 15:06:03.694 | DEBUG    | __main__:hereToChromeCDP:640 - WebSocket ID: e6f742c2-f2b9-4e28-8bdf-7a537ac33092 - Processing large message of size 80693 bytes
2025-11-15 15:06:05.264 | INFO     | __main__:stats_thread_func:704 - Connections: Active count 1 of max 10, Total processed: 132.
2025-11-15 15:06:05.266 | INFO     | __main__:stats_thread_func:727 - Process info: 1 child processes
2025-11-15 15:06:08.268 | INFO     | __main__:stats_thread_func:704 - Connections: Active count 1 of max 10, Total processed: 132.
2025-11-15 15:06:08.270 | INFO     | __main__:stats_thread_func:727 - Process info: 1 child processes
2025-11-15 15:06:08.739 | DEBUG    | __main__:hereToChromeCDP:640 - WebSocket ID: e6f742c2-f2b9-4e28-8bdf-7a537ac33092 - Processing large message of size 67250 bytes
2025-11-15 15:06:08.779 | DEBUG    | __main__:hereToChromeCDP:640 - WebSocket ID: e6f742c2-f2b9-4e28-8bdf-7a537ac33092 - Processing large message of size 80693 bytes
2025-11-15 15:06:08.914 | DEBUG    | __main__:hereToChromeCDP:640 - WebSocket ID: e6f742c2-f2b9-4e28-8bdf-7a537ac33092 - Processing large message of size 160293 bytes
2025-11-15 15:06:08.968 | DEBUG    | __main__:stats_disconnect:284 - Websocket 611eff89-fc06-44a9-a2bd-9dee72f18870 - Connection ended, processed in 11.964s
2025-11-15 15:06:08.968 | DEBUG    | __main__:cleanup_chrome_by_pid:297 - WebSocket ID: 611eff89-fc06-44a9-a2bd-9dee72f18870 Cleaning up Chrome subprocess PID 7557
2025-11-15 15:06:08.969 | DEBUG    | __main__:cleanup_chrome_by_pid:318 - WebSocket ID: 611eff89-fc06-44a9-a2bd-9dee72f18870 - Killing 3 Chrome child processes
2025-11-15 15:06:08.969 | ERROR    | __main__:cleanup_chrome_by_pid:377 - WebSocket ID: 611eff89-fc06-44a9-a2bd-9dee72f18870 - Error in Chrome cleanup: Passing coroutines is forbidden, use tasks explicitly.
2025-11-15 15:06:08.969 | DEBUG    | __main__:close_socket:268 - WebSocket: 611eff89-fc06-44a9-a2bd-9dee72f18870 Closing websocket to puppeteer
2025-11-15 15:06:08.977 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 611eff89-fc06-44a9-a2bd-9dee72f18870 Chrome stderr PID 7557: [1115/150608.977642:ERROR:zygote_communication_linux.cc(290)] Failed to send GetTerminationStatus message to zygote
2025-11-15 15:06:08.978 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 611eff89-fc06-44a9-a2bd-9dee72f18870 Chrome stderr PID 7557: [1115/150608.978207:ERROR:gpu_process_host.cc(984)] GPU process launch failed: error_code=1002
2025-11-15 15:06:08.978 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 611eff89-fc06-44a9-a2bd-9dee72f18870 Chrome stderr PID 7557: [1115/150608.978525:ERROR:gpu_process_host.cc(984)] GPU process launch failed: error_code=1002
2025-11-15 15:06:08.978 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 611eff89-fc06-44a9-a2bd-9dee72f18870 Chrome stderr PID 7557: [1115/150608.978846:ERROR:gpu_process_host.cc(984)] GPU process launch failed: error_code=1002
2025-11-15 15:06:08.979 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 611eff89-fc06-44a9-a2bd-9dee72f18870 Chrome stderr PID 7557: [1115/150608.979129:ERROR:gpu_process_host.cc(984)] GPU process launch failed: error_code=1002
2025-11-15 15:06:08.979 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 611eff89-fc06-44a9-a2bd-9dee72f18870 Chrome stderr PID 7557: [1115/150608.979373:ERROR:gpu_process_host.cc(984)] GPU process launch failed: error_code=1002
2025-11-15 15:06:08.979 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 611eff89-fc06-44a9-a2bd-9dee72f18870 Chrome stderr PID 7557: [1115/150608.979736:ERROR:gpu_process_host.cc(984)] GPU process launch failed: error_code=1002
2025-11-15 15:06:08.980 | CRITICAL | __main__:log_stream:220 - WebSocket ID: 611eff89-fc06-44a9-a2bd-9dee72f18870 Chrome stderr PID 7557: [1115/150608.979743:FATAL:gpu_data_manager_impl_private.cc(448)] GPU process isn't usable. Goodbye.
2025-11-15 15:06:09.245 | DEBUG    | __main__:hereToChromeCDP:653 - WebSocket ID: e6f742c2-f2b9-4e28-8bdf-7a537ac33092 - Connection closed normally while sending
```

**Comment by Ramalama2** [comment]
sockpuppetbrowser is just crap, sorry but it has a ton of issues.
i use playwrite with chromium for similar website grabbing approach in another projects and it works perfectly fine.

However, for the dbus error the fix is pretty easy, i simply modify the container with:

```
FROM dgtlmoon/sockpuppetbrowser:latest
USER root
RUN apk add --no-cache dbus
COPY start-dbus.sh /usr/local/bin/start-dbus.sh
RUN chmod +x /usr/local/bin/start-dbus.sh
USER chrome
ENTRYPOINT ["/bin/sh","/usr/local/bin/start-dbus.sh"]
```

and the start-dbus.sh script:
```
#!/bin/sh
set -eu
export DBUS_SYSTEM_BUS_ADDRESS="unix:path=/tmp/dbus-system-bus"
if [ ! -S /tmp/dbus-system-bus ]; then
  dbus-daemon --session --nofork --nopidfile --address="$DBUS_SYSTEM_BUS_ADDRESS" >/tmp/dbus.log 2>&1 &
fi
exec /usr/local/bin/entrypoint.sh
```

And use this environment variable simply:
```
TZ=Europe/Berlin
SCREEN_WIDTH=1920
SCREEN_HEIGHT=1080
SCREEN_DEPTH=16
DBUS_SYSTEM_BUS_ADDRESS=unix:path=/tmp/dbus-system-bus
LIBGL_ALWAYS_SOFTWARE=1
```
(You need only the DBUS one)


For the lazy people, i use docker containers for myself with script, if anyone want it:

cat scripts/update_browser-sockpuppet.sh
```
#!/bin/bash

imagename=browser-sockpuppet-chrome
dockerlink=dgtlmoon/sockpuppetbrowser:latest
local_image=${imagename}:local

tr_enable=false
ddir=/server/$imagename
mnt_arguments="--env-file $ddir/environment.list"
run_args="--shm-size=1g --security-opt seccomp=$ddir/chrome.json --cap-add=SYS_ADMIN"

docker stop $imagename
docker rm $imagename
dockerlink_src="$(echo "$dockerlink" | cut -d':' -f1)"
CONTAINER_image_id="$(docker images --format="{{.Repository}} {{.ID}}" | grep "^$dockerlink_src" | cut -d' ' -f2)"
docker image rm $local_image 2>/dev/null || true
#docker image rm $CONTAINER_image_id
docker pull $dockerlink
docker build --pull -t $local_image $ddir
docker run -l traefik.enable=$tr_enable \
$run_args -i -t -d --network=web --name=$imagename --restart=always $mnt_arguments $local_image
```

------

But this will only fix the dbus errors, which arent a big issue anyway.
Otherwise i would highly recommend a proper chrome docker container from someone else.

(for myself, im using my playwrite LXC Container, that i have anyway, which works without any issues at all)
But i cant share it, that would be simply too much for here and for normal people.

Cheers

**Comment by Ramalama2** [comment]
i found a better alternative that works without any errors:

cat update_browserless.sh
```
#!/bin/bash

imagename=browserless
dockerlink=ghcr.io/browserless/chrome:latest

tr_enable=false
ddir=/server/$imagename
mnt_arguments="--env-file $ddir/environment.list"
run_args="--tmpfs /tmp:rw,noexec,nosuid,size=2048m"

docker stop $imagename
docker rm $imagename
dockerlink_src="$(echo "$dockerlink" | cut -d':' -f1)"
CONTAINER_image_id="$(docker images --format="{{.Repository}} {{.ID}}" | grep "^$dockerlink_src" | cut -d' ' -f2)"
#docker image rm $CONTAINER_image_id
docker pull $dockerlink
docker run -l traefik.enable=$tr_enable \
$run_args -i -t -d --network=web --name=$imagename --restart=always $mnt_arguments $dockerlink
```

cat /server/browserless/environment.list
```
TZ=Europe/Berlin
SCREEN_WIDTH=1920
SCREEN_HEIGHT=1080
SCREEN_DEPTH=16
ENABLE_DEBUGGER=false
HOST=browserless
PORT=3000
EXTERNAL_URL=http://browserless:3000
```

And for changedetection.io environment:
```
PLAYWRIGHT_DRIVER_URL=ws://browserless:3000/chrome?launch=%7B%22headless%22%3Atrue%7D
SOCKETIO_MODE=gevent
```

Cheers
